### ISSUE TITLE
Could not find a file named "pubspec.yaml" in .pub_cache/git/common_utils.dart

### ISSUE THREAD

**Issue by natejgardner** [tekartik/sqflite_more#37]
On running `pub get` with
```
dependencies:
  sqflite_common_porter:
    git:
      url: git://github.com/tekartik/sqflite_more
      ref: null_safety
      path: sqflite_common_porter
    version: '>=0.2.0'
```

Get the error:
```
Running "flutter pub get" in project...                   
Could not find a file named "pubspec.yaml" in "E:\flutter\.pub-cache\git\common_utils.dart-2e75c15393e827bd5df73513e9659a309cae9c04".
pub get failed (66; Could not find a file named "pubspec.yaml" in "E:\flutter\.pub-cache\git\common_utils.dart-2e75c15393e827bd5df73513e9659a309cae9c04".)
Process finished with exit code 66
```

Seems there's a dependency issue with fetching `common_utils.dart`.

**Comment by alextekartik** [comment]
Yes I think I wrongly used `git://` in my public git dependencies. You should changed the dependency to:

````yaml
dependencies:
  sqflite_common_porter:
    git:
      url: https://github.com/tekartik/sqflite_more
      ref: dart2_3
      path: sqflite_common_porter
    version: '>=0.2.0'
````

See [versioning doc](https://github.com/tekartik/common.dart/blob/main/doc/tekartik_versioning.md) to understand how I personnally deal with git dependency (that might require tweaks in the future)
